# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2019 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.                                                                                                         
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

version: '2.1'

services:

  test-database:
    image: postgres:9.4.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbpass123
      - POSTGRES_USER=inspirehep
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "pg_isready --dbname=inspirehep --host=localhost --username=inspirehep"

  unit:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/code
    command: ["python", "-m", "pytest", "tests/unit"]

  integration:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/code
    command: ["python", "-m", "pytest", "tests/integration"]
    depends_on:
      test-database:
        condition: service_healthy
    links:
      - test-database
    environment:
      - APP_SQLALCHEMY_DATABASE_URI=postgresql://inspirehep:dbpass123@test-database:5432/inspirehep
